//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int id { get; set; }
        public string ho { get; set; }
        public string ten { get; set; }
        public string taikhoan { get; set; }
        public string matkhau { get; set; }
    }
}
