//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_BenhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuocHen
    {
        public int id { get; set; }
        public int id_bacsi { get; set; }
        public int id_benhnhan { get; set; }
        public int id_nganh { get; set; }
        public string ngay { get; set; }
        public string thoigian { get; set; }
        public string mota { get; set; }
        public Nullable<bool> isDuyet { get; set; }
    
        public virtual BacSi BacSi { get; set; }
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual Nganh Nganh { get; set; }
    }
}
